ReqManager/Controllers/RequestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReqManager.Models;
using System.Linq;
using System.Security.Claims;

namespace ReqManager.Controllers
{
    public class RequestsController : Controller
    {
        private readonly RequestDbContext _context;

        public RequestsController(RequestDbContext context)
        {
            _context = context;
        }

        // GET: Requests
        [Authorize]
        public IActionResult Index()
        {
            if (User.IsInRole("Client"))
            {
                // Get the email address of the currently logged-in client
                string currentClientEmail = User.Identity.Name;

                // Filter requests to only show those created by the current client
                var clientRequests = _context.Requests.Where(r => r.CreatedBy == currentClientEmail).ToList();

                return View(clientRequests);
            } else 
            {
                var reqs = _context.Requests.ToList();
                return View(reqs);
            }
        }

        // GET: Requests/Details/5
        public ActionResult Details(int id)
        {
            var request = _context.Requests.FirstOrDefault(x => x.Id == id);
            return View(request);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Requests/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RequestModel requestmodel)
        {
            if (ModelState.IsValid)
            {
                requestmodel.Created = DateTime.Now;
                requestmodel.Status = RequestStatus.Open;

                requestmodel.CreatedBy = User.Identity.Name;

                _context.Requests.Add(requestmodel);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(requestmodel);
        }

        // GET: Requests/Edit/5
        public ActionResult Edit(int id)
        {
            var request = _context.Requests.FirstOrDefault(x => x.Id == id);
            return View(request);
        }

        // POST: Requests/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, RequestModel requestmodel)
        {
            if (ModelState.IsValid)
            {
                var existingRequest = _context.Requests.FirstOrDefault(x => x.Id == id);
                existingRequest.Description = requestmodel.Description;
                existingRequest.ShortDescription = requestmodel.ShortDescription;
                existingRequest.Comment = requestmodel.Comment;
                existingRequest.Status = requestmodel.Status;

                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(requestmodel);
        }

        // GET: Requests/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var request = _context.Requests.FirstOrDefault(x => x.Id == id);
            return View(request);
        }

        // POST: Requests/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var request = _context.Requests.FirstOrDefault(x => x.Id == id);
            _context.Requests.Remove(request);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ReqManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReqManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReqManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Requests" asp-action="Index">ReqManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ReqManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>